name: Leaderboard

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
        pipenv install --python "3.11" --dev --system --skip-lock
    - name: Run Jupyter
      run: |
        mkdir jupyter
        jupyter nbconvert --to html --output jupyter/index.html --execute leaderboard.ipynb
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: leaderboard
        path: |
          jupyter/index.html
        retention-days: 5
    - name: Upload Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./jupyter
