name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
        pipenv install --python "3.12" --dev --system --skip-lock
    - name: Lint with Mypy
      run: mypy .
    - name: Lint with Ruff
      uses: chartboost/ruff-action@v1
    - name: Run LLMFAO
      run: python3 -m llmfao --help
